creators:
  - username: "edstarginfiniteet"
    chat_id: "-1003605752690"
  - username: "michelleperry71"
    chat_id: "-1003605752690"
  - username: "rebelsoulrudegyal"
    chat_id: "-1003605752690"
  - username: "pricetopay_firsteye"
    chat_id: "-1003605752690"
  - username: "truthseeker4blindsouls"
    chat_id: "-1003605752690"
  - username: "neo58328"
    chat_id: "-1003605752690"
  - username: "rudegyalrebelsoul"
    chat_id: "-1003605752690"
  - username: "edwardhoward93"
    chat_id: "-1003605752690"
  - username: "ccbaby016"
    chat_id: "-1003605752690"
  - username: "knowthywayout"
    chat_id: "-1003605752690"
  - username: "luckylarry80"
    chat_id: "-1003605752690"
  - username: "godkillerware1"
    chat_id: "-1003605752690"
  - username: "price2payforsharingfacts"
    chat_id: "-1003605752690"
  - username: "allanssd5"
    chat_id: "-1003605752690"